version: '3'
services:
  web:
    container_name: web-server
    build:
      context: web
    networks:
      - app-network
    volumes:
      - ../:/var/www/html/
    ports:
      - 8080:80

  db:
    container_name: db-server
    build:
      context: db
    networks:
      - app-network
    ports:
      - 6000:3306

networks:
  app-network:
    driver: bridge 
